[build]
command = ""

[env.production]
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-11-17"

[env.preview]
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-11-17"

